### ISSUE TITLE
Idea extract static styles into StyleSheet using PPX

### ISSUE THREAD

**Issue by jfrolich** [rescript-react-native/rescript-react-native#637]
## The problem

Especially on react-native-web you should write styles in a StyleSheet so the styles are extracted and much more efficient. However, I really like to write inline styles (am I the only one?).

## Considered solution

An optional PPX that hoist static styles (by analyzing if there are variables etc.) into a top level StyleSheet.

**Comment by MoOx** [comment]
A huge discussion happened here https://github.com/rescript-react-native/rescript-react-native/pull/739

**Comment by MoOx** [comment]
I guess we should focus on a PPX free solution as discussed there. We can continue to discuss in #667

**Comment by jfrolich** [comment]
Well, this wouldn't be possible without a `ppx`. It's more of an optimization for production apps when you use inline styles versus top level `StyleSheet`'s. I might look into it at some point in the future if we run into performance issues :)
