### ISSUE TITLE
Discussion for process for release (for all repo)

### ISSUE THREAD

**Issue by MoOx** [rescript-react-native/rescript-react-native#670]
@sgny I saw that you cut some release (which is nice).

I am most of the time using "npmpub" (a simple tool I maintain - https://github.com/MoOx/npmpub) that is inside devDep of most repo, to cut release like this

- bump in package.json by hand
- prepare changelog with the same version number
- commit
- call `yarn release` (which is alias for `npmpub` in most repo of this org)

In addition to making the npm release, this also do
- create a git tag
- create a GitHub release with the notes from the changelog

This last part is interesting cause tools & people can watch for release & be alerted when a new release is published via GitHub.

Do you think we could agree on something similar, especially to have git tag/github release?
My tool is just a simple thing I made a few years ago and that still works without too much maintenance, I am totally ok to ditch this in favour of another process that can bring us the same result: one command for npm + tag + GitHub release

**Comment by sgny** [comment]
@MoOx I hadn't checked into `npmpub` before the recent security alerts and noticed it was your work. I don't have any issues with that. Having release tags is very useful and I haven't been doing that for a long time.

I did publish a few packages, but I'll adopt `npmpub` before proceeding further.

**Comment by MoOx** [comment]
Ok nice. If you find anything wrong with this package, be sure to get in touch with me :) 
I am always open to find a better solution.

**Comment by sgny** [comment]
Is it reasonable to presume a global install of `npmpub` cannot be used to publish individual packages?

**Comment by MoOx** [comment]
Maybe but the version used can change the way the changelog is being parsed.
Maybe a given version could be added to a single local dep that include the package used for "tooling" (lint-staged, husky etc).

**Comment by MoOx** [comment]
It's been a while I am alone on most of the org. I will handle that by myself until someone wants to help.
