### ISSUE TITLE
Replace poly variants that use @as with strings

### ISSUE THREAD

**Issue by MoOx** [rescript-react-native/rescript-react-native#748]
## The problem

When using poly variants for string enums, we transformed a lot of "string-with-dash" to camel case stringWithoutDash, relying on ReScript `@as` annotation.
Now that ReScript allows poly variants to have string syntax, we could  change this choice to make it more straight forward to new ReScript user that are familiar with React Native.

## Considered solution

We could make this a breaking change. Maybe a codemod will help.

## Alternatives solutions

We can also:

* add strings values (so people can use both syntax (with-dash or withoutDash) and keep both (maintenance++)
* integrate both & deprecate later withoutDash if that possible (syntax seems to be accepted but it doesn't seems to show the warning - I tested  `| @deprecated("use #\"plain-text\" instead of #plainText") @as("plain-text") #plainText` in `Alert.res`)

**Comment by cknitt** [comment]
A big advantage of a breaking change would be that we could define the types for such poly variants in one place instead of having to copy them everywhere.

E.g., instead of having

```rescript
  ~importantForAccessibility: @string
  [
    | #auto
    | #yes
    | #no
    | @as("no-hide-descendants") #noHideDescendants
  ]=?,
```

in every component binding, we can define

```rescript
type importantForAccessibility = [ | #auto | #yes | #no | #"no-hide-descendants" ]
```

in a single place.

**Comment by MoOx** [comment]
Yesss!
