### ISSUE TITLE
Revert the Platform.os changes?

### ISSUE THREAD

**Issue by cknitt** [rescript-react-native/rescript-react-native#778]
In #771 and #774, I changed `Platform.os` from an abstract type to a polymorphic variant.

This allows us to use the more convenient

```rescript
if Platform.os === #ios {
  ...
}
```

instead of

```rescript
if Platform.os === Platform.ios {
  ...
}
```

which is fine.

It also allows us to do

```rescript
switch Platform.os {
  | #ios => ...
  | #android => ...
  | _ => ...
}
```

which is problematic as it compiles to something like

```
var match = ReactNative.Platform.OS;

if (match === "ios") {
  ...
} else if (match === "android") {
  ...
} else {
  ...
}
```

which will break Metro bundler's inlining (see a previous discussion in #239 for more details about this).

So I am not sure anymore if we should introduce a breaking change that invites people to use a problematic pattern. What do you think @MoOx?

**Comment by MoOx** [comment]
I guess if we document this that can be enough ?

**Comment by cknitt** [comment]
Documenting it is the alternative, yes. If you prefer that, let's go that way.

**Comment by cknitt** [comment]
Leaving this open as a reminder for the documentation. 🙂

**Comment by cknitt** [comment]
What we could do though is add the existing constants `Platform.ios` etc. for compatibility (to be deprecated and removed later). What do you think, @MoOx?

**Comment by cknitt** [comment]
Ah, no, that won't work, polymorphic variants cannot have `@inline`.
