### ISSUE TITLE
The plan to support JSX v4

### ISSUE THREAD

**Issue by pd4d10** [rescript-react-native/rescript-react-native#790]
## The problem

rescript@10.1.0 and @rescript/react@0.11.0 have supported JSX v4. Wondering if there is any plan about this.

## Considered solution

Support JSX v4 and bump a major version.

## Alternatives solutions

Stay at v3

**Comment by fhammerschmidt** [comment]
It is supported already. Is there anything that does not work for you?

**Comment by fhammerschmidt** [comment]
As long as you have the current version of rescript-react-native (0.70.0) installed, this change should just work. At work, we use it for quite some time now with JSX v4 (and automatic mode, but that should not matter).

**Comment by adolfogc** [comment]
Hi, making the change in the `bsconfig.json` file results in the following error when compiling:

```bash
Error: Unsupported jsx version 4
```

I am using version 0.72.

**Comment by Freddy03h** [comment]
Done with #811
